---
- hosts: bitcoin_nodes
  vars_files:
    - "{{ playbook_dir }}/user_input.yml"
  become: True
  tasks:

    - name: Lightning node tasks
      when: lightning_node_vars["enabled"] | default(False) | bool
      include_role:
        name: lightning_node

    - name: Lightning addon tasks
      when: lightning_addons_vars["enabled"] | default(False) | bool
      include_role:
        name: lightning_addons
