---
- name: Ensure linux_service_user is present
  user:
    name: "{{ linux_service_user }}"
    shell: bash
    create_home: true

- name: Ensure all necessary files and directories exist before proceeding
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    user: "{{ linux_service_user }}"
  loop:
    - { "path": "{{ bitcoin_node_vars['data_dir'] }}", "state": "directory" }
    - { "path": "{{ bitcoin_node_vars['code_dir'] }}", "state": "directory" }
    - { "path": "{{ bitcoin_node_vars['config_dir'] }}", "state": "directory" }
    - { "path": "{{ bitcoin_node_vars['logging_dir'] }}", "state": "directory" }
    - { "path": "{{ bitcoin_node_vars['config_dir'] }}/bitcoin.conf", "state": "file" }
    - { "path": "{{ bitcoin_node_vars['logging_dir'] }}/debug.log", "state": "file" }

- name: block device reformat (disabled by default)
  when:
    - bitcoin_node_vars["reformat_device"] | default(false) | bool
    - bitcoin_node_vars["device_path"] | default(false) | bool
  include_tasks:
    name: reformat_block_device.yml

- name: git clone bitcoin source code
  git:
    repo: 'https://github.com/bitcoin/bitcoin.git'
    dest: "{{ bitcoin_node_vars['code_dir'] }}"
    clone: True

- name: Install Berkeley database
  shell:
    cmd: "{{ bitcoin_node_vars['code_dir'] }}/bitcoin/contrib/install_db4.sh \
          {{ bitcoin_node_vars['code_dir'] }}/bitcoin"

- name: Execute autogen.sh and configure from bitcoin git repo, then make + make install (this takes a very long time!)
  shell:
    cmd:
      - "git checkout tags/{{ bitcoin_node_vars['bitcoin_git_tag'] }} && \
         ./autogen.sh"
      - "export BDB_PREFIX=\"{{ bitcoin_node_vars['code_dir'] }}/bitcoin/db4\" && \
         ./configure BDB_LIBS=\"-L${BDB_PREFIX}/lib -ldb_cxx-4.8\" BDB_CFLAGS=\"-I${BDB_PREFIX}/include\""
      - "make; sudo make install"
  args:
    chdir: "{{ bitcoin_node_vars['code_dir'] }}/bitcoin"

- name: template bitcoin.conf configuration file
  template:
    src: bitcoin.conf.j2
    dest: "{{ bitcoin_node_vars['config_dir'] }}/bitcoin.conf"
    user: "{{ linux_service_user }}"

- name: SystemD service configuration
  when: update_systemd | default(False) | bool
  block:

    - name: template bitcoind systemd unit file
      template:
        src: bitcoind.service.j2
        dest: /etc/systemd/system/bitcoind.service

    - name: start bitcoind.service
      register: bitcoind_systemctl_start
      systemd:
        state: started
        enabled: True
        name: bitcoind.service
        daemon_reload: True

    - name: mask systemd units that could interrupt node operation
      systemd:
        state: masked
        name: "{{ item }}"
      loop:
        - "sleep.target"
        - "suspend.target"
        - "hibernate.target"
        - "hybrid-sleep.target"

    - name: restart logind
      systemd:
        state: restarted
        name: "systemd-logind.service"

- name: Finished, display status
  debug:
    var: bitcoind_systemctl_start