---
- name: Verify essential values from user_input.yml
  assert:
    fail_msg: "User_input.yml file corrupted and/or missing key information. Re-installing this repository is advised."
    that:
      - bitcoin_node_vars["enabled"]
      - bitcoin_node_vars["data_dir"] is defined
      - bitcoin_node_vars["node_name"] is defined
      - bitcoin_node_vars["config_dir"] is defined
      - bitcoin_node_vars["logging_dir"] is defined
      - bitcoin_node_vars["full_compile"] is defined
      - bitcoin_node_vars["update_systemd"] is defined

- name: Debian-type OS prerequisites and pre-flight checks
  when: ansible_os_family == "Debian"
  include_tasks:
    file: pre_steps_debian.yml

- name: RedHat-type OS prerequisites and pre-flight checks
  when: ansible_os_family == "RedHat"
  include_tasks:
    file: pre_steps_redhat.yml

- name: bitcoin node compile and install
  when: bitcoin_node_vars["full_compile"] | default(False) | bool
  include_tasks:
    file: bitcoin_node_compile_install.yml


