---
- name: install EPEL repo
  dnf:
    name: epel-release
    state: latest

# Since the powertools repo is named "crb" in some distributions, just attempt to enable all of them.
- name: enable powertools repo
  ignore_errors: True
  shell:
    cmd: "dnf config-manager --set-enabled powertools crb"

- name: bitcoin build dependencies dnf package install
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - curl
    - bzip2
    - bzip2-libs
    - gcc-c++
    - libtool
    - make
    - autoconf
    - automake
    - patch
    - libevent-devel
    - boost-devel
    - python3-devel
    - miniupnpc-devel
    - zeromq-devel
    - qt5-qttools-devel
    - qt5-qtbase-devel
    - qrencode-devel
    - sqlite-devel