---
- name: bitcoin build dependencies debian package install
  apt:
    state: present
    name: "{{ item }}"
    update_cache: True
    install_recommends: True
  loop:
    - git
    - curl
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - pkg-config
    - bsdmainutils
    - python3
    - libevent-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - libboost-thread-dev
    - libsqlite3-dev
    - libminiupnpc-dev
    - libzmq3-dev
    - libqt5gui5
    - libqt5core5a
    - libqt5dbus5
    - qttools5-dev
    - qttools5-dev-tools
    - libqrencode-dev
