- name: Debian-type OS prerequisites and bitcoin core compile pre-flight checks
  when:
    - ansible_os_family == 'Debian'
  block:

    - name: x86 build dependencies debian package install
      when: ansible_architecture == 'x86_64'
      apt:
        state: present
        name: "{{ item }}"
        update_cache: True
        install_recommends: True
      loop: "{{ debian_x86['basic_packages'] + debian_x86['btc_core_compile_packages'] }}"

    - name: aarch64 build dependencies debian package install
      when: ansible_architecture == 'aarch64'
      apt:
        state: present
        name: "{{ item }}"
        update_cache: True
        install_recommends: True
      loop: "{{ debian_aarch64['basic_packages'] + debian_aarch64['btc_core_compile_packages'] }}"


- name: x86 RedHat-type OS prerequisites and bitcoin core compile pre-flight checks
  when:
    - ansible_os_family == "RedHat"
    - ansible_architecture == 'x86_64'
  block:

    - name: install EPEL repo
      dnf:
        name: epel-release
        state: latest

    # Since the powertools repo is named "crb" in some distributions, just attempt to enable all of them.
    - name: enable powertools repo
      ignore_errors: True
      shell:
        cmd: "dnf config-manager --set-enabled powertools crb"

    - name: x86 build dependencies dnf package install
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ redhat_x86['basic_packages'] +  redhat_x86['btc_core_compile_packages'] }}"
