- name: detect existing bitcoind command
  register: which_bitcoind
  shell: "which bitcoind"
  failed_when:
    - which_bitcoind.rc != 0
    - "'no bitcoind in' in which_bitcoind.stdout"

- name: x86 Debian-type OS prerequisites and LND compile pre-flight checks
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'x86_64'
  block:

    - name: Download Go (golang) for debian x86
      when: lightning_node_vars['install_golang'] | bool
      register: golang_download_debian_x86
      get_url:
        url: "{{ debian_x86['golang']['source_url'] }}"
        checksum: "sha256:{{ debian_x86['golang']['sha256sum'] }}"
        dest: "/home/{{ linux_service_user }}/"
        # decompress is only supported on ansible-2.14 which is not easily installed on ubuntu
        # decompress: True

    - name: x86 build dependencies debian package install
      apt:
        state: present
        name: "{{ item }}"
        update_cache: True
        install_recommends: True
      loop: "{{ debian_x86['basic_packages'] + debian_x86['lnd_compile_packages'] }}"

    - name: Install Go (golang) for debian x86
      when: lightning_node_vars['install_golang'] | bool
      unarchive:
        src: "{{ golang_download_debian_x86['dest'] }}"
        dest: "/home/{{ linux_service_user }}"
        owner: "{{ linux_service_user }}"
        group: "{{ linux_service_user }}"

    - name: remove golang_download archive after installing to GOPATH
      file:
        path: "{{ golang_download_debian_x86['dest'] }}"
        state: absent
        force: True

- name: aarch64 Debian-type OS prerequisites and LND compile pre-flight checks
  when:
    - ansible_os_family == 'Debian'
    - ansible_architecture == 'aarch64'
  block:

    - name: Download Go (golang) for debian aarch64
      when: lightning_node_vars['install_golang'] | bool
      register: golang_download_debian_aarch64
      get_url:
        url: "{{ debian_aarch64['golang']['source_url'] }}"
        checksum: "sha256:{{ debian_aarch64['golang']['sha256sum'] }}"
        dest: "/home/{{ linux_service_user }}"
        # decompress is only supported on ansible-2.14 which is not easily installed on ubuntu
        # decompress: True

    - name: aarch64 build dependencies debian package install
      apt:
        state: present
        name: "{{ item }}"
        update_cache: True
        install_recommends: True
      loop: "{{ debian_aarch64['basic_packages'] + debian_aarch64['lnd_compile_packages'] }}"

    - name: Install Go (golang) for debian aarch64
      when: lightning_node_vars['install_golang'] | bool
      unarchive:
        src: "{{ golang_download_debian_aarch64['dest'] }}"
        dest: "/home/{{ linux_service_user }}"
        owner: "{{ linux_service_user }}"
        group: "{{ linux_service_user }}"

    - name: remove golang_download archive after installing to GOPATH
      file:
        path: "{{ golang_download_debian_aarch64['dest'] }}"
        state: absent
        force: True


- name: x86 RedHat-type OS prerequisites and LND compile pre-flight checks
  when:
    - ansible_os_family == "RedHat"
    - ansible_architecture == 'x86_64'
  block:

    - name: Download Go (golang) for redhat x86
      when: lightning_node_vars['install_golang'] | bool
      register: golang_download_redhat_x86
      get_url:
        url: "{{ redhat_x86['golang']['source_url'] }}"
        checksum: "sha256:{{ redhat_x86['golang']['sha256sum'] }}"
        dest: "/home/{{ linux_service_user }}/"
        # decompress is only supported on ansible-2.14 which is not easily installed on ubuntu
        # decompress: True

    - name: x86 build dependencies dnf package install
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ redhat_x86['basic_packages'] +  redhat_x86['lnd_compile_packages'] }}"

    - name: Install Go (golang) for redhat x86
      when: lightning_node_vars['install_golang'] | bool
      unarchive:
        src: "{{ golang_download_redhat_x86['dest'] }}"
        dest: "/home/{{ linux_service_user }}"
        owner: "{{ linux_service_user }}"
        group: "{{ linux_service_user }}"

    - name: remove golang_download archive after installing to GOPATH
      file:
        path: "{{ golang_download_redhat_x86['dest'] }}"
        state: absent
        force: True

- name: Set GOPATH environment variable via .bashrc
  when: lightning_node_vars['install_golang'] | bool
  lineinfile:
    path: "/home/{{ linux_service_user }}/.bashrc"
    line: "export GOPATH=/home/{{ linux_service_user }}/go"
    regexp: "^export GOPATH"

- name: append GOPATH to PATH environment variable via .bashrc
  when: lightning_node_vars['install_golang'] | bool
  lineinfile:
    path: "/home/{{ linux_service_user }}/.bashrc"
    line: "export PATH=$PATH:$GOPATH/bin"
